language: node_js
services:
- postgresql
node_js:
- stable
- "lts/*"
matrix:
  fast_finish: true
  allow_failures:
  - node_js: stable
env:
  matrix:
  - CMD=lint
  - CMD=test
before_install:
- export TZ=Asia/Tokyo
script:
- yarn $CMD
notifications:
  email: false
